### PR TITLE
Editorial: Prefix names of intrinsics

### LINKED ISSUE #842: Should intrinsics be scoped?
TL;DR: Is there anything speaking for, or against, renaming the intrinsics established in ECMA-402 to follow the form `%Intl.Foo%`? 

This may not be hugely important within the spec document itself, but personally I would appreciate if any references to those intrinsics in engine code can be more easily identified as `Intl`-related.

This may need input from the ECMA-262 editors - the closest relevant thing I could find is https://github.com/tc39/ecma262/commit/8f67a13e1af599fb31047c6f8e35acd7586d1bd1, which possibly sets a precedent for the names of intrinsics to match what they are referenced as from the outside world. The current Temporal draft spec uses `%Temporal.Foo%` for each constructor, opposed to a plain `%Foo%` name.

### PR DESCRIPTION
**Pull request by linusg**
Closes #842.

Not sure if the same naming scheme is appropriate for `%SegmentIteratorPrototype%` and `%SegmentsPrototype%`, but happy update those as well if wanted.

### CODE REVIEW

**Comment by ljharb** [comment]
The rule is that anything that's accessible off of a top-level intrinsic, should be - so if `%Segments%` exists, then i'd expect `%Segments.prototype%`, etc.

**Comment by linusg** [comment]
`%Segments%` doesn't exist, the object is created directly in an AO (https://tc39.es/ecma402/#sec-createsegmentsobject):

```
1. Let internalSlotsList be « [[SegmentsSegmenter]], [[SegmentsString]] ».
2. Let segments be OrdinaryObjectCreate(%SegmentsPrototype%, internalSlotsList).
```

Same for `%SegmentIteratorPrototype%` (https://tc39.es/ecma402/#sec-createsegmentiterator):

```
1. Let internalSlotsList be « [[IteratingSegmenter]], [[IteratedString]], [[IteratedStringNextSegmentCodeUnitIndex]] ».
2. Let iterator be OrdinaryObjectCreate(%SegmentIteratorPrototype%, internalSlotsList).
```

**Comment by ljharb** [comment]
Gotcha; then those two would remain as-is.

**Review by gibson042 — COMMENTED** [review]
Thanks, this is great! I'm thinking it also needs to include [`oldids`](https://tc39.es/ecmarkup/#oldids) attributes for preserving any current inbound links, and possibly renaming %SegmentsPrototype% to %IntlSegmentsPrototype% and %SegmentIteratorPrototype% to %IntlSegmentIteratorPrototype% as well.

**Comment by linusg** [comment]
Done! I don't think any IDs are changed by the first commit (all links reference the public names already), but I've included `oldids` in the second change.

**Review by gibson042 — APPROVED** [review]

**Pull request merged**
