### PR TITLE
Editorial: Note about BiDi concerns

### PR DESCRIPTION
**Pull request by littledan**
This note came out of the Internationalization WG review of ECMA-402
in the 2018 TPAC meeting.

### CODE REVIEW

**Comment by littledan** [comment]
cc @aphillips

**Comment by littledan** [comment]
Rather than saying this for specific APIs, we concluded that we should instead make a single high-level note to explain best practices for interpolation and BiDi, as this isn't quite related to specific APIs https://www.w3.org/International/articles/inline-bidi-markup/

**Comment by littledan** [comment]
We discussed this issue in the November 2018 ECMA-402 meeting, and the conclusion was, we should include a note specification-wide. The issue here is not specific to a particular formatter, but rather universal to working with strings in a BiDi context.

Would anyone be interested in writing such a note?

**Comment by aphillips** [comment]
@littledan I'd be interested, in part because I'm writing one in my day job about the same thing.

A tricky thing here is that if all the browsers supported bidi isolation ([glances at mostly at Edge and a bit at Webkit](https://w3c.github.io/i18n-tests/results/the-dir-attribute-isolation)) and the isolating controls ([glances at _everyone_ except Firefox](https://w3c.github.io/i18n-tests/results/bidi-algorithm#rli_etc)), a lot of the complexity would go out of providing support for bidi string assembly. Since we all expect that support to be forthcoming, the note will necessarily have a "legacy browser" and "non-legacy browser" section to it.

**Comment by littledan** [comment]
OK, then I'll close this PR, and I look forward to @aphillips 's new text for this clarification.

**Comment by zbraniecki** [comment]
@aphillips - did you ever get to write a spec-wide version of this note?

**Pull request closed without merging**
