### PR TITLE
FormatToParts: aggregation of PR #64 and PR #79

### PR DESCRIPTION
**Pull request by caridy**
DateTimeFormat.prototype.formatToParts()
* https://github.com/tc39/ecma402/pull/64

NumberFormat.prototype.formatToParts(): 
* https://github.com/tc39/ecma402/pull/79

These features are Stage 4, and are ready to be merged.

### CODE REVIEW

**Comment by caridy** [comment]
closes #79 and closes #64

**Comment by zbraniecki** [comment]
@caridy - I think you skipped in your aggregation the whole part of the NumberFormat patch that changed `PartitionNumberPattern` algo to return a `List`.

**Comment by caridy** [comment]
hmm, where was that?

**Comment by zbraniecki** [comment]
@caridy Look at the algo in the merged spec: https://github.com/tc39/ecma402/blob/master/spec/numberformat.html#L114-L148 vs the algo in the PR: https://github.com/stasm/ecma402/blob/number-format-to-parts/spec/numberformat.html#L114-L199

I didn't check if the rest of aggregated PR matches the orignal PRs, but this is definitely missing and makes the spec broken because callers expect this algo to return parts now, while in the spec it returns a string.

**Comment by caridy** [comment]
I will review in details tomorrow.

**Pull request merged**
