### PR TITLE
Normative: Correct Gregorian calendar BC(E) era to signed years less than 1 AD

### LINKED ISSUE #723: Wrong era for ISO year 0 in Gregorian calendar
In the [[Era]] row of https://tc39.es/ecma402/#table-datetimeformat-tolocaltime-record:

> Let `year` be `YearFromTime(tz)` specified in es2023's [Year Number](https://tc39.es/ecma262/#sec-year-number). If year is less than 0, return 'BC', else, return 'AD'.

This should be "less than 1" because ISO year 0 is the year 1 BC (or 1 BCE if you prefer the "common era" nomenclature). There is no year 0 BC or 0 AD.

I ran a quick check with eshost, and none of the engines that I have installed implement the spec as written:
```
$ eshost -e 'new Date(Date.parse("+000000-01-01")).toLocaleDateString(undefined, {era:"short", timeZone:"UTC"})'
#### ChakraCore
1 1, 1 BC

#### engine262

Error: Date.prototype.toLocaleDateString is not implemented

#### GraalJS
1/1/1 BC

#### JavaScriptCore
1 1, 1 BC

#### Moddable XS
Fri Dec 31 -0001

#### QuickJS
12/31/-0001

#### SpiderMonkey
1/1/1 B

#### V8
1/1/1 BC
```
As you can see, output varies quite a lot, but for all the engines that do include an era in the output, it is always BC for ISO year 0. So this change would reflect web reality.

(Spotted by @gibson042.)

### PR DESCRIPTION
**Pull request by gibson042**
Fixes #723

### CODE REVIEW

**Comment by gibson042** [comment]
test262 PR: https://github.com/tc39/test262/pull/3722

**Review by ptomato — APPROVED** [review]
It's my understanding that this is correct, and represents existing web reality.

**Review by ryzokuken — APPROVED** [review]

**Comment by sffc** [comment]
TG2 consensus: https://github.com/tc39/ecma402/blob/master/meetings/notes-2022-12-08.md#normative-correct-gregorian-calendar-bce-era-to-signed-years-less-than-1-ad-729

**Comment by gibson042** [comment]
This change achieved consensus at the TC39 plenary of 2023-01-31.

**Pull request merged**
