### PR TITLE
Update agenda-2017-12-15.md

### PR DESCRIPTION
**Pull request by fabalbon**
Add link to a spreadsheet with Google's interests and mid-term goals.

### CODE REVIEW

**Comment by anba** [comment]
The spreadsheet doesn't seem to be public.

**Comment by littledan** [comment]
I'll merge the patch once the permissions are fixed.

**Comment by littledan** [comment]
I see you changed the patch, but I still don't have access to the spreadsheet. You can test locally whether permissions have been made public by opening the document in an incognito window. You might want to try making the document with a non-google.com account if you're having trouble making it public with a google.com account.

**Comment by fabalbon** [comment]
I just updated the link, sorry for that.

**Comment by littledan** [comment]
Thanks for the quick fix. Interesting agenda!

**Pull request merged**
