### PR TITLE
Intl.DateTimeFormat should localize era names as well

### PR DESCRIPTION
**Pull request by watilde**
Related issue: https://github.com/tc39/ecma402/issues/88

### CODE REVIEW

**Comment by caridy** [comment]
LGTM.

**Comment by littledan** [comment]
Has anyone written test262 tests for this change?

**Comment by caridy** [comment]
I was planning to do so, or get @watilde (who has been very responsive to help). Additionally, we can get implementers to contribute back their existing tests since `era` is already supported in Chrome, FF and IE/Edge.

**Comment by watilde** [comment]
Wow, I should add the test case to test262 at the same time when I wrote this change. Sure thing, I will try to update the test case to cover this patch!

**Pull request merged**
