### PR TITLE
Update formatToParts proposals links

### PR DESCRIPTION
**Pull request by rxaviers**

### CODE REVIEW

**Comment by caridy** [comment]
actually, we need to transfer those two repos to tc39 org. @zbraniecki can you start the transfer to @bterlson asap?

**Comment by zbraniecki** [comment]
transferred.

**Comment by bterlson** [comment]
And done :)

**Comment by caridy** [comment]
@rxaviers can you update the PR to use the new links?

**Comment by rxaviers** [comment]
Done. :)

PS: Note, both use the same link.

**Pull request merged**
