### PR TITLE
Normative: Make @@toStringTag values more meaningful

### LINKED ISSUE #176: Why are the toStringTag values "Object"?
It would seem more intuitive that, for example, `Intl.Collator[Symbol.toStringTag]` would be `"Intl.Collator"`. Is this done for compatibility reasons, where we're aware of a site that depends on `toString()` on Intl objects returning `"[Object object]"`? For new APIs, should we use `"Object"` or the name of the class, if we're not constrained by compatibility?

### PR DESCRIPTION
**Pull request by shvaikalesh**
Resolves #176.

If this reaches consensus, I will proceed with `test262` coverage and WebKit implementation.

_cc_ @littledan @Ms2ger

### CODE REVIEW

**Comment by Ms2ger** [comment]
This seems fine to me in theory, but the main question is if implementers will implement it.

**Comment by shvaikalesh** [comment]
V8, JSC, and SpiderMonkey follow the current spec (except `Intl.PluralRules[Symbol.toStringTag]` is not defined in Firefox 75).

I am sure that with a few failing tests that are easy to fix, implementations will come.

**Comment by sffc** [comment]
Thanks for this; I think browsers will implement it.  I added it to the agenda to discuss at the next TG2 call, and then we can have it approved at the June TC39.

**Comment by littledan** [comment]
I'm in favor of this; I bet it'll be web-compatible, but we could roll it back if needed.

**Comment by leobalter** [comment]
@shvaikalesh I believe this will be well accepted. It would be very helpful if you could add the respective coverage in Test262. This way we have a good status of matching conformance and perhaps a vision of (non) breaking challenges.

**Comment by FrankYFTang** [comment]
We need to update the following test262 tests right after we land this PR

intl402/Collator/instance-class.js
intl402/Collator/prototype/builtin.js
intl402/DateTimeFormat/prototype/builtin.js
intl402/DateTimeFormat/instance-class.js
intl402/NumberFormat/prototype/builtin.js
intl402/NumberFormat/instance-class.js
intl402/NumberFormat/prototype/toStringTag/configurable.js
intl402/NumberFormat/prototype/toStringTag/prop-desc.js
intl402/PluralRules/prototype/builtins.js

**Comment by shvaikalesh** [comment]
@FrankYFTang Thank you for extensive list, I will make sure to update those in https://github.com/tc39/test262/pull/2634.

**Comment by FrankYFTang** [comment]
FYI - bug for v8 to sync with this PR https://bugs.chromium.org/p/v8/issues/detail?id=10554

**Comment by leobalter** [comment]
> Is this a thing we want to document in [Annex B - Additions and Changes That Introduce Incompatibilities with Prior Editions](https://tc39.es/ecma402/#annex-incompatibilities)?

yes, we need to add that.

@shvaikalesh would you mind adding it?

**Comment by FrankYFTang** [comment]
TC39 reach consensus this morning.

**Pull request merged**
