### PR TITLE
Editorial: Use consistent wording for List interactions

### PR DESCRIPTION
**Pull request by gibson042**
Align with ECMA-262:
* https://github.com/tc39/ecma262/commit/2df27d363f9622193d5100d769039dde47a9fa64
* https://github.com/tc39/ecma262/pull/2152

### CODE REVIEW

**Comment by ben-allen** [comment]
I'm wondering if by analogy to this change in 262:

```<p>When an algorithm iterates over the elements of a List without specifying an order, the order used is the order of the elements in the List.</p>```


we should add a sentence about how unless specified otherwise tables are iterated in table order, and then remove all the instances of `, in table order,` from loops

**Review by ben-allen — CHANGES_REQUESTED** [review]
To my eye it looks like there's a couple you've missed, but this is otherwise fantastic

**Comment by sffc** [comment]
@gibson042 Can you take a look at @ben-allen's feedback? This looks almost mergeable.

**Comment by gibson042** [comment]
@ben-allen please re-review!

> I've found a couple of other examples of the wording you're fixing:
> 
> negotiation.html:64: `1. If _canonicalizedTag_ is not an element of _seen_, append _canonicalizedTag_ as the last element of _seen_.`
> 
> negotiation.html:270: `1. If _availableLocale_ is not *undefined*, append _locale_ to the end of _subset_.`

Thanks; fixed.

> I'm wondering if by analogy to this change in 262:
> 
> `<p>When an algorithm iterates over the elements of a List without specifying an order, the order used is the order of the elements in the List.</p>`
> 
> we should add a sentence about how unless specified otherwise tables are iterated in table order, and then remove all the instances of `, in table order,` from loops

I've held off on doing this because I can't find a satisfactory way that is both in scope and discoverable—the latter characteristic being important, and handled in ECMA-262 by internal cross referencing (note how e.g. [FindViaPredicate](https://tc39.es/ecma262/multipage/indexed-collections.html#sec-findviapredicate) step 4 iterates over _indices_, which is defined in either step 2 or 3 to be a [List](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-list-and-record-specification-type) with a link to the very section establishing the "_When an algorithm iterates over the elements of a List without specifying an order, the order used is the order of the elements in the List_" convention). We can pursue this in a followup.

**Review by ben-allen — APPROVED** [review]

**Pull request merged**
