### PR TITLE
Normative: Use ListFormat for Array.prototype.toLocaleString

### PR DESCRIPTION
**Pull request by FrankYFTang**
This PR address https://github.com/tc39/ecma402/issues/422

### CODE REVIEW

**Review by anba — CHANGES_REQUESTED** [review]
The `options` parameter conflict described in #422 is still unresolved.

**Review by ryzokuken — APPROVED** [review]
+1, I agree with @zbraniecki

**Comment by FrankYFTang** [comment]
We discussed this in the 2021-11-04 TG2 and I feel there are still other concerns which need to be addressed. But I don't think I could address them myself. I would leave this to whoever want to take it from here to work on that.

**Comment by sffc** [comment]
See the issue #422 for additional discussion

**Comment by sffc** [comment]
2022-05-19: This issue is too large for a PR; it should have a proposal. See #422. Volunteers would be appreciated.

**Pull request closed without merging**
