### PR TITLE
Add step ResolveLocale 8.h.ii.2.b

### PR DESCRIPTION
**Pull request by FrankYFTang**
@littledan @anba @gsathya @Ms2ger 
Close https://github.com/tc39/ecma402/issues/223

### CODE REVIEW

**Comment by FrankYFTang** [comment]
Ping

**Comment by FrankYFTang** [comment]
> Let's get tests out for review in test262, and double-check that the committee wants this change.

I am not sure what you are suggesting here.  Currently, with the spec without this PR, the following test in test262
test/intl402/Collator/missing-unicode-ext-value-defaults-to-true.js
expect the collator.resolvedOptions().locale without "-kn" for "en-u-co-phonebk-kn" or "en-u-kn-co-phonebk"

        assert.sameValue(locale.indexOf("-kn"), -1, "\"kn\" is returned in locale, but shouldn't be.");

I don't think that make sense. Since in the same test it also expect collator.resolvedOptions().numeric to be true.

I can work on a PR to change test/intl402/Collator/missing-unicode-ext-value-defaults-to-true.js AFTER we merge this PR first.

**Comment by littledan** [comment]
Yes, I agree the current spec is weird. I would just like to get broader buy-in on this change before merging.

**Comment by FrankYFTang** [comment]
@zbraniecki

**Comment by FrankYFTang** [comment]
ping

**Comment by FrankYFTang** [comment]
so my understand from our meeting today is we will take this one line change in the spec and lead the #311 for future consideration. Can we merge this now?

**Comment by littledan** [comment]
That matches my understanding as well; merging this patch

**Comment by rkirsling** [comment]
Am I correct in understanding that this change was only meant to address `de-u-kn` not losing its `-u-kn`, and was not meant to affect the `de-u-kn-true` case? Because that's what #223 says, and that's what the spec appears to say, but it's not what tc39/test262#1995 says—the test was changed to require that the explicit `-true` of `de-u-kn-true` be dropped, which seems very unexpected.

**Comment by anba** [comment]
The test262 PR may have been conflating #223 with the canonicalisation changes from `Intl.Locale`? But dropping `-true` is now correct according to the current draft spec, because we're now performing [UTS35 canonicalisation](https://unicode.org/reports/tr35/#Canonical_Unicode_Locale_Identifiers), which removes `"true"` values from all `type` productions.

**Comment by rkirsling** [comment]
Thanks for the clarification, @anba! Looks like #406 got merged in the time since I asked the question above. 😅Glad that it's ultimately an accurate test.

**Pull request merged**
