### PR TITLE
Add proposal for Intl.NumberFormat round option

### PR DESCRIPTION
**Pull request by rxaviers**
Allows to select a rounding function for NumberFormat different than round "half-even". For example: ceil, floor, or truncate.

See: https://github.com/rxaviers/ecma402-number-format-round-option

### CODE REVIEW

**Comment by rwaldron** [comment]
Something's up with this one? I think it needs a rebase

**Comment by rxaviers** [comment]
Done.

**Comment by caridy** [comment]
ops, I have fixed the link from the previous merge on https://github.com/tc39/ecma402/commit/546f48185ceac585051233c4f4719897061aaab6, you will have to rebase again!

**Comment by rxaviers** [comment]
No problem. Done.

**Comment by rxaviers** [comment]
Created https://github.com/rxaviers/ecma402-number-format-round-option/issues/1 as a poll for discussion for the "Proposal for stage 0".

**Comment by jzaefferer** [comment]
Anything holding up a merge for this? It only adds a link...

**Pull request merged**
