### PR TITLE
Meta: update actions SHAs to long hashes

### LINKED ISSUE #542: The spec was not build and sync with the tree after 2021-02-11
I notice none of the commit after
Create notes-2021-02-11.md 8488eb7856298dee86d8e2f9de049841805e87f9
got build successfully and sync into https://tc39.es/ecma402/

For example, the following are not in there
spec: GetOption reform for ECMA 2021 (#538) … @ryzokuken  
Normative: Adding Intl.DateTimeFormat formatRange/formatRangeToParts … @fabalbon
Normative: Use OrdinaryHasInstance in normative optional steps (#500) @shvaikalesh
Do not allow duplicate variants within the tlang component of a trans… … @jswalden

@ryzokuken, @fabalbon  @shvaikalesh , @sffc , @jswalden 

It break start on https://github.com/tc39/ecma402/runs/1923390814

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #542

### CODE REVIEW

**Comment by FrankYFTang** [comment]
It turn out leo is fixing that in https://github.com/tc39/ecma402/pull/539 @ljharb  - could you review that PR instead?

**Comment by ljharb** [comment]
True, but that one's also fixing some spec stuff :-) either PR is fine.

**Comment by leobalter** [comment]
@ljharb Thanks! I prefer the change in my PR using `@main` instead of the whole SHA. Otherwise I'd land your changes here.

**Comment by leobalter** [comment]
Please let me know if we should avoid the current usage or anything. Otherwise I'm closing this for now.

**Pull request closed without merging**
