### PR TITLE
Normative: Add Lower case mapping definition in 6.1

### PR DESCRIPTION
**Pull request by FrankYFTang**
Address https://github.com/tc39/ecma402/issues/576

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
seems good to me

**Review by leobalter — APPROVED** [review]

**Comment by sffc** [comment]
2021-06-03 TG2 consensus: https://github.com/tc39/ecma402/blob/master/meetings/notes-2021-06-03.md#normative-add-lower-case-mapping-definition-in-61

**Review by sffc — APPROVED** [review]

**Review by ryzokuken — APPROVED** [review]
IIUC, this is normative but doesn't change web reality, right? It's just specifying currently unspecified things? (uppercase to lowercase conversion)

**Comment by FrankYFTang** [comment]
> IIUC, this is normative but doesn't change web reality, right? It's just specifying currently unspecified things? (uppercase to lowercase conversion)

yes, that is the case.

**Comment by FrankYFTang** [comment]
@ryzokuken - I saw you assign this to me, could you please explicitly tell me what you expect me to do for this PR now? I am not sure what is the expectation. Thanks

**Comment by ryzokuken** [comment]
well, I didn't mean it in a way that you need to do something for this one right now, just that you're assigned to the overall PR. I will present this PR to TG-1 tomorrow after which we can merge this :D

**Comment by ryzokuken** [comment]
2021-07-13: TG1 consensus at the July TC39 meeting.

Merging this because it has TG1 and TG2 consensus and multiple positive reviews.

**Pull request merged**
