### PR TITLE
Meta: Change "Difficult" to "Expensive" in Stage 2 entrance criterion

### PR DESCRIPTION
**Pull request by sffc**

### CODE REVIEW

**Review by FrankYFTang — APPROVED** [review]

**Review by leobalter — APPROVED** [review]
I'm not blocking the approval on my nit picking. It seems good to land one way or another.

**Review by ryzokuken — APPROVED** [review]
LGTM either way (wrt @leobalter's suggestion).

**Review by zbraniecki — APPROVED** [review]
`suggestion(optional)`: since we're revisiting it, would you be open to adjust `the same level ...` part?

As of now this sounds like if a proposal is at least on par with the cost of third party, it is passing the bar. I believe our intent here is to say that it has to be significantly more expensive to do X with third-party to pass the bar on extending the standard.

**Comment by sffc** [comment]
I rewrote the whole sentence to read:

> Features in Intl must be significantly more efficient and less complex than a third-party library implementing the same feature.

Does this address your concern @zbraniecki ?

**Comment by ryzokuken** [comment]
ping @zbraniecki

**Review by zbraniecki — APPROVED** [review]
lgtm! Thank you for addressing my comment

**Pull request merged**
